In [1]:
import pandas as pd
import numpy as np
import os
import random

# Data Preparation

In [89]:
fakultas = []

for i in os.listdir("data_csv"):
    fakultas.append(i[:-4])

In [90]:
container = []
# Create df

df_FEB = pd.read_csv("data_csv/FEB.csv")
df_FH = pd.read_csv("data_csv/FH.csv")
df_FIB = pd.read_csv("data_csv/FIB.csv")
df_FISIP = pd.read_csv("data_csv/FISIP.csv")
df_FK = pd.read_csv("data_csv/FK.csv")
df_FKIP = pd.read_csv("data_csv/FKIP.csv")
df_FKOR = pd.read_csv("data_csv/FKOR.csv")
df_FMIPA = pd.read_csv("data_csv/FMIPA.csv")
df_FP = pd.read_csv("data_csv/FP.csv")
df_FSRD = pd.read_csv("data_csv/FSRD.csv")
df_FT = pd.read_csv("data_csv/FT.csv")
df_SV = pd.read_csv("data_csv/SV.csv")

container.extend([df_FEB, df_FH, df_FIB, df_FISIP, df_FK, df_FKIP, df_FKOR, df_FMIPA, df_FP, df_FSRD, df_FT, df_SV])

In [91]:
# Add fakutlas COlumn

for data, fak in zip(container, fakultas):
    data["Fakultas"] = fak

In [92]:
df_FH

                         Nama Lengkap     Jalur Masuk Jenis Kelamin Fakultas
0                 ADALIA SAFIRA RAHMA     UTBK SBMPTN     Perempuan       FH
1    Adityas Challysta Joan Paramitha  SM Jalur Ujian     Perempuan       FH
2                Aida Rizkiatul Zahra     UTBK SBMPTN     Perempuan       FH
3                 Aisya Violeta Putri     UTBK SBMPTN     Perempuan       FH
4                Almira Salma Idellia          SNMPTN     Perempuan       FH
..                                ...             ...           ...      ...
102      Yulius Ananda Yudis Praditya     UTBK SBMPTN     Laki-laki       FH
103                      Zahra Fadila     UTBK SBMPTN     Perempuan       FH
104                  Zahra Suryandaru     UTBK SBMPTN     Perempuan       FH
105                  Zalfa Hania Alya     UTBK SBMPTN     Perempuan       FH
106                  Zalfa Hania Alya     UTBK SBMPTN     Perempuan       FH

[107 rows x 4 columns]

#### Clear duplicate Value

In [94]:
for i in container:
    try:
        i.drop_duplicates(subset ="Nama Lengkap",
                         keep='last', inplace = True)
    except:
        pass

In [95]:
# Fix df_FH agar columns-nya sama

df_FH.drop(['Fakultas'], axis = 1, inplace=True)

In [96]:
df_FH["Program Studi"] = "Hukum"
df_FH["Fakultas"] = "FH"

In [97]:
df_FH

,Nama Lengkap,Jalur Masuk,Jenis Kelamin,Program Studi,Fakultas
0,ADALIA SAFIRA RAHMA,UTBK SBMPTN,Perempuan,Hukum,FH
1,Adityas Challysta Joan Paramitha,SM Jalur Ujian,Perempuan,Hukum,FH
2,Aida Rizkiatul Zahra,UTBK SBMPTN,Perempuan,Hukum,FH
3,Aisya Violeta Putri,UTBK SBMPTN,Perempuan,Hukum,FH
4,Almira Salma Idellia,SNMPTN,Perempuan,Hukum,FH
...,...,...,...,...,...
101,Yohanes Christian Kamengyeti,UTBK SBMPTN,Laki-laki,Hukum,FH
102,Yulius Ananda Yudis Praditya,UTBK SBMPTN,Laki-laki,Hukum,FH
103,Zahra Fadila,UTBK SBMPTN,Perempuan,Hukum,FH
104,Zahra Suryandaru,UTBK SBMPTN,Perempuan,Hukum,FH
106,Zalfa Hania Alya,UTBK SBMPTN,Perempuan,Hukum,FH

#### Jumlah maba tiap jurusan

In [207]:
import math
sum = 0

for i in container:
    print(f"{i.Fakultas[0]}\t= {i.shape[0]}\t{round(i.shape[0]/(6279/38))}")
    sum += i.shape[0]

print(f"\nTotal = {sum}")

FEB	= 551	3
FH	= 105	1
FIB	= 338	2
FISIP	= 316	2
FK	= 254	2
FKIP	= 1692	10
FKOR	= 228	1
FMIPA	= 466	3
FP	= 624	4
FSRD	= 221	1
FT	= 667	4
SV	= 817	5

Total = 6279

In [102]:
fakultas

['FEB',
 'FH',
 'FIB',
 'FISIP',
 'FK',
 'FKIP',
 'FKOR',
 'FMIPA',
 'FP',
 'FSRD',
 'FT',
 'SV']

#### Convert to Dictionary

In [208]:
data_dict = {}

for i in fakultas:
    data_dict[i] = []

In [209]:
data_dict

{'FEB': [],
 'FH': [],
 'FIB': [],
 'FISIP': [],
 'FK': [],
 'FKIP': [],
 'FKOR': [],
 'FMIPA': [],
 'FP': [],
 'FSRD': [],
 'FT': [],
 'SV': []}

In [210]:
data_list = [i.values.tolist() for i in container]

In [211]:
for i in data_list:
    print(i[:1])
    print("")

[['Abel Rizky Agustian', 'UTBK SBMPTN', 'Laki-laki', 'Akuntansi', 'FEB']]

[['ADALIA SAFIRA RAHMA', 'UTBK SBMPTN', 'Perempuan', 'Hukum', 'FH']]

[['ABDURRAHMAN DARMAKUSUMA PARAMADUTA', 'UTBK SBMPTN', 'Laki-laki', 'Ilmu Sejarah', 'FIB']]

[['Adena Fatihani', 'SM Jalur Nilai UTBK', 'Perempuan', 'Hubungan Internasional', 'FISIP']]

[['Adelia Friska Andrian', 'UTBK SBMPTN', 'Perempuan', 'Kedokteran', 'FK']]

[['ABDULLAH NUR YASIN', 'UTBK SBMPTN', 'Laki-laki', 'Bimbingan Konseling', 'FKIP']]

[['Ilham.khanid003@gmain.com', 'SNMPTN', 'Laki-laki', 'Pendidikan Jasmani Kesehatan dan Rekreasi', 'FKOR']]

[['Adelia Dita Pratiwi', 'UTBK SBMPTN', 'Perempuan', 'Biologi', 'FMIPA']]

[['ADHIKA YUDHA PRAMUDYA', 'SM Jalur Nilai UTBK', 'Laki-laki', 'Agribisnis', 'FP']]

[['Adinda Nur Chasanah', 'UTBK SBMPTN', 'Perempuan', 'Desain Interior', 'FSRD']]

[['Ade Fitria Yupa', 'SM Jalur Ujian', 'Perempuan', 'Arsitektur', 'FT']]

[['Adhelia Kusumawardhani', 'PMDK', 'Perempuan', 'D3 Agribisnis', 'SV']]

In [212]:
for per_fak in data_list:
    for i in per_fak:
        data_dict[i[4]].append(i)

In [213]:
# shuffle the data

for i in data_dict.keys():
    data_dict[i] = random.sample(data_dict[i], len(data_dict[i]))

In [214]:
len(data_dict["SV"])

817

# Algoritma

In [215]:
data_dict["FEB"][0:4]

[['Khurina Roihan Akhsani', 'UTBK SBMPTN', 'Perempuan', 'Akuntansi', 'FEB'],
 ['Jeremy Juni Wilson Saragih',
  'SM Jalur Ujian',
  'Laki-laki',
  'Ekonomi Pembangunan',
  'FEB'],
 ['Ananda Sofiatun Anariyah', 'SNMPTN', 'Perempuan', 'Manajemen', 'FEB'],
 ['Sucitra Ediyah Meilani', 'SNMPTN', 'Perempuan', 'Akuntansi', 'FEB']]

In [216]:
kelompok_dict = {}

for i in range(1,300):
    kelompok_dict[i] = []
    check_temp = []
    iteration = 0
    while len(kelompok_dict[i]) < 38:
        for x in fakultas:
            if len(kelompok_dict[i]) == 38:
                break
            try:
                if x == "FH" or x == "FKOR" or x == "FSRD":
                    kelompok_dict[i].append(data_dict[x][0])
                    data_dict[x].pop(0)
                    if len(kelompok_dict[i]) == 38:
                        break
                elif x == "FEB" or x == "FMIPA":
                    for _ in range(3):
                        kelompok_dict[i].append(data_dict[x][0])
                        data_dict[x].pop(0)
                        if len(kelompok_dict[i]) == 38:
                            break
                elif x == "FIB" or x == "FISIP" or x == "FK":
                    for _ in range(2):
                        kelompok_dict[i].append(data_dict[x][0])
                        data_dict[x].pop(0)
                        if len(kelompok_dict[i]) == 38:
                            break
                elif x == "FKIP":
                    for _ in range(10):
                        kelompok_dict[i].append(data_dict[x][0])
                        data_dict[x].pop(0)
                        if len(kelompok_dict[i]) == 38:
                            break
                elif x == "FP" or x == "FT":
                    for _ in range(4):
                        kelompok_dict[i].append(data_dict[x][0])
                        data_dict[x].pop(0)
                        if len(kelompok_dict[i]) == 38:
                            break
                elif x == "SV":
                    for _ in range(5):
                        kelompok_dict[i].append(data_dict[x][0])
                        data_dict[x].pop(0)
                        if len(kelompok_dict[i]) == 38:
                            break
            except:
                continue
        iteration += 1
            
    print(f"Sukses {i}")

print("Sukses")

Sukses 1
Sukses 2
Sukses 3
Sukses 4
Sukses 5
Sukses 6
Sukses 7
Sukses 8
Sukses 9
Sukses 10
Sukses 11
Sukses 12
Sukses 13
Sukses 14
Sukses 15
Sukses 16
Sukses 17
Sukses 18
Sukses 19
Sukses 20
Sukses 21
Sukses 22
Sukses 23
Sukses 24
Sukses 25
Sukses 26
Sukses 27
Sukses 28
Sukses 29
Sukses 30
Sukses 31
Sukses 32
Sukses 33
Sukses 34
Sukses 35
Sukses 36
Sukses 37
Sukses 38
Sukses 39
Sukses 40
Sukses 41
Sukses 42
Sukses 43
Sukses 44
Sukses 45
Sukses 46
Sukses 47
Sukses 48
Sukses 49
Sukses 50
Sukses 51
Sukses 52
Sukses 53
Sukses 54
Sukses 55
Sukses 56
Sukses 57
Sukses 58
Sukses 59
Sukses 60
Sukses 61
Sukses 62
Sukses 63
Sukses 64
Sukses 65
Sukses 66
Sukses 67
Sukses 68
Sukses 69
Sukses 70
Sukses 71
Sukses 72
Sukses 73
Sukses 74
Sukses 75
Sukses 76
Sukses 77
Sukses 78
Sukses 79
Sukses 80
Sukses 81
Sukses 82
Sukses 83
Sukses 84
Sukses 85
Sukses 86
Sukses 87
Sukses 88
Sukses 89
Sukses 90
Sukses 91
Sukses 92
Sukses 93
Sukses 94
Sukses 95
Sukses 96
Sukses 97
Sukses 98
Sukses 99
Sukses 100
Sukses 101
Sukses 102
Sukses 103
Sukses 104
Sukses 105
Sukses 106
Sukses 107
Sukses 108
Sukses 109
Sukses 110
Sukses 111
Sukses 112
Sukses 113
Sukses 114
Sukses 115
Sukses 116
Sukses 117
Sukses 118
Sukses 119
Sukses 120
Sukses 121
Sukses 122
Sukses 123
Sukses 124
Sukses 125
Sukses 126
Sukses 127
Sukses 128
Sukses 129
Sukses 130
Sukses 131
Sukses 132
Sukses 133
Sukses 134
Sukses 135
Sukses 136
Sukses 137
Sukses 138
Sukses 139
Sukses 140
Sukses 141
Sukses 142
Sukses 143
Sukses 144
Sukses 145
Sukses 146
Sukses 147
Sukses 148
Sukses 149
Sukses 150
Sukses 151
Sukses 152
Sukses 153
Sukses 154
Sukses 155
Sukses 156
Sukses 157
Sukses 158
Sukses 159
Sukses 160
Sukses 161
Sukses 162
Sukses 163
Sukses 164
Sukses 165

KeyboardInterrupt:

In [194]:
#kelompok_dict = {}

#for i in range(1,300):
#    kelompok_dict[i] = []
#    check_temp = []
#    iteration = 0
#    while len(kelompok_dict[i]) < 38:
#        for x in fakultas:
#            if len(kelompok_dict[i]) == 38:
#                break
#            try:
#                if (iteration > 0) and (x == "FH"):
#                    pass
#                elif (iteration > 1) and (x == "FISIP" or x == "FK" or x == "FKOR" or x == "FSRD"):
#                    pass
#                elif (iteration > 2) and (x == "FMIPA" or x == "FIB"):
#                    pass
#                elif (iteration > 3) and (x == "FP" or x == "FEB"):
#                    pass
#                elif (iteration > 4) and (x == "FT"):
#                    pass
#                elif (iteration > 5) and (x == "FSRD"):
#                    pass
#                else:
#                    kelompok_dict[i].append(data_dict[x][0])
#                    data_dict[x].pop(0)
#            except:
#                continue
#        iteration += 1
#            
#    print(f"Sukses {i}")

#print("Sukses")

In [217]:
# Cek apakah ada data yang tertinggal 

for i in data_dict.keys():
    print(len(data_dict[i]))

0
0
0
0
0
0
0
0
0
0
0
0

# Export to CSV

In [218]:
import csv

a_file = open("bismillah2.csv", "w", newline='')

writer = csv.writer(a_file)
writer.writerow(["kelompok","data"])
for key, value in kelompok_dict.items():
    for i in value:
        writer.writerow([key, i])

a_file.close()

In [220]:
df_FH

,Nama Lengkap,Jalur Masuk,Jenis Kelamin,Program Studi,Fakultas
0,ADALIA SAFIRA RAHMA,UTBK SBMPTN,Perempuan,Hukum,FH
1,Adityas Challysta Joan Paramitha,SM Jalur Ujian,Perempuan,Hukum,FH
2,Aida Rizkiatul Zahra,UTBK SBMPTN,Perempuan,Hukum,FH
3,Aisya Violeta Putri,UTBK SBMPTN,Perempuan,Hukum,FH
4,Almira Salma Idellia,SNMPTN,Perempuan,Hukum,FH
...,...,...,...,...,...
101,Yohanes Christian Kamengyeti,UTBK SBMPTN,Laki-laki,Hukum,FH
102,Yulius Ananda Yudis Praditya,UTBK SBMPTN,Laki-laki,Hukum,FH
103,Zahra Fadila,UTBK SBMPTN,Perempuan,Hukum,FH
104,Zahra Suryandaru,UTBK SBMPTN,Perempuan,Hukum,FH
106,Zalfa Hania Alya,UTBK SBMPTN,Perempuan,Hukum,FH

In [224]:
! pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.0.7-py2.py3-none-any.whl (243 kB)
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.7

WARNING: You are using pip version 21.0.1; however, version 21.1.3 is available.
You should consider upgrading via the 'c:\users\legion\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

In [225]:
df_FH.to_excel("data_csv/Lul.xlsx")

In [227]:
for i in container:
    i.to_excel(f"data_csv/{i.Fakultas[0]}.xlsx")